### PR TITLE
Fixed unbound methods getting their first parameter curried

### PR DESCRIPTION
**Pull request by epsy**
Tests and fixes issue #2.

### CODE REVIEW

**Comment by aliles** [comment]
_Just clarifying I understand what is being fixed here._

The change from the `unbound method` type for methods on uninstantiated classes in Python2 to ordinary `function` objects in Python3 results in the `self` argument being present in the `funcsigs.Signature` object of Python3 but not Python2. This pull request fixes that.

Is this accurate?

**Comment by epsy** [comment]
Yes.

It also makes `self` a positional-only parameter on Python 2 unbound method, which might be surprising at first, but as they cannot receive `self` as a named argument, unlike on regular functions as returned in the equivalent Python 3 function, it really does become a positional-only parameter like inspect defines it.

**Comment by aliles** [comment]
Terrific, thank you for the patch. I will publish a new release to PyPI in the next couple of days, if that is ok.

**Comment by epsy** [comment]
Great, thanks.

**Comment by epsy** [comment]
Hello again, do you think you could schedule a release on PyPI soon?

**Comment by aliles** [comment]
Oh my, well that's embarrassing. This had completely fallen of my todo list.

I have just published the [0.4 release](https://pypi.python.org/pypi/funcsigs/0.4) to PyPI. I have also published [wheel packages](http://pythonwheels.com/) in addition to source bundles, which will hopefully speed your deployments.

Very sorry for the time this has taken, this has been a bit of a fail as a project maintainer.

**Pull request merged**
