### PR TITLE
Fix typo in README.rst

### PR DESCRIPTION
**Pull request by lesteve**
compat**a**bility -> compat**i**bility

### CODE REVIEW

**Comment by rbtcollins** [comment]
Thanks for this; its a dupe though - and the other one has been merged over in the testing-cabal/funcsigs fork.

**Comment by lesteve** [comment]
Fair enough, I'll close this PR then.

Out of interest, which repo is supposed to be the reference one for funcsigs ? I assumed it was aliles/funcsigs since that's the one that is linked on PyPI and readthedocs but your answer seem to imply that cabal/funcsigs is more up-to-date.

**Comment by rbtcollins** [comment]
It was alilies/funcsigs, but he's moved onto other things, and @harlowja
and I are picking the project up. Will be updating pypi when we cut a
release.

On 1 April 2016 at 02:31, Loïc Estève notifications@github.com wrote:

> Closed #17 https://github.com/aliles/funcsigs/pull/17.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/aliles/funcsigs/pull/17#event-609797770

## 

Robert Collins rbtcollins@hpe.com
Distinguished Technologist
HP Converged Cloud

**Comment by lesteve** [comment]
OK thanks for the details !

**Pull request closed without merging**
